### ISSUE TITLE
porttimer的移植问题

### ISSUE THREAD

**Issue by johnzhy** [Alidong/HAL_FreeRTOS_Modbus#1]
timer = xTimerCreate(
      "Master timer",
      (50 * usT35TimeOut50us) / (1000 * 1000 / configTICK_RATE_HZ) + 1, pdFALSE,
      (void *)1, timer_timeout_ind);

这里，configTICK_RATE_HZ默认是1000，也就是除数如果小于1000，那么前面一堆算出来的就是0，也就是你的定时器最小周期是1ms，而真正需要的定时器周期应该是50us，所以要么rtos的周期调快，到1MHz（或者到20KHz好像也行），要么就只能使用硬件定时器了。
不知道我的理解对不对。

**Comment by Alidong** [comment]
是的，考虑到低端32的定时器资源过于紧缺，这里推荐使用软定时器以节省资源。虽然这样会造成定时的精度不够，但经过测试，绝大部分modbus设备都能成功通讯。
